# fly.toml file for n8n
app = "mainframe-qpny-g"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
PORT = 5678

[http_service]
  internal_port       = 5678
  force_https         = true
  auto_stop_machines  = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source      = "n8n_data"
  destination = "/home/node/.n8n"
